### ISSUE TITLE
Cannot find the `run.pl` file

### ISSUE THREAD

**Issue by a11to1n3** [mc-lovin-mlem/concept-embeddings-and-ilp#2]
Hi,

I have so far achieved the Aleph explanations for my custom models and cannot find the `run.pl` file to proceed further.

Is it true that the file must be provided somewhere in the codebase or do I have to create one? If the latter applies, could you so me how to write that file?

Looking forward to your response!

Best,

Anh-Duy Pham

**Comment by mc-lovin-mlem** [comment]
Hi Anh-Duy,

we will look further into this issue but here is the content needed in the run.pl file:

:- [aleph], read_all(faces), induce.
:- halt.

Simply copy this code in a text file, save it and rename it to 'run.pl' . Then proceed as described in the readme.

Best and good luck
Johannes

**Comment by a11to1n3** [comment]
Hi Johannes,

thank you for your prompt reply. I could basically run the induction with Aleph thanks to your support. However, Aleph itself yields errors which I'm not very familiar with:

`ERROR: /home/duyduyduy/Documents/concept-embeddings-and-ilp/experiments/ilp/resnet50a4e5fcba_2022-03-05_193601490481/aleph.pl:97:
ERROR:    Wrong context: arithmetic_function/1 can only be used in a directive
Warning: /home/duyduyduy/Documents/concept-embeddings-and-ilp/experiments/ilp/resnet50a4e5fcba_2022-03-05_193601490481/aleph.pl:97:
Warning:    Goal (directive) failed: user:(prolog_type(_704),init(_704))
Warning: /home/duyduyduy/Documents/concept-embeddings-and-ilp/experiments/ilp/resnet50a4e5fcba_2022-03-05_193601490481/aleph.pl:1149:
Warning:    Singleton variable in branch: HOVars
Warning:    Singleton variable in branch: Recursion
Warning: /home/duyduyduy/Documents/concept-embeddings-and-ilp/experiments/ilp/resnet50a4e5fcba_2022-03-05_193601490481/aleph.pl:2034:
Warning:    Singleton variable in branch: PC
Warning: /home/duyduyduy/Documents/concept-embeddings-and-ilp/experiments/ilp/resnet50a4e5fcba_2022-03-05_193601490481/aleph.pl:3999:
Warning:    Singleton variable in branch: D
Warning: /home/duyduyduy/Documents/concept-embeddings-and-ilp/experiments/ilp/resnet50a4e5fcba_2022-03-05_193601490481/aleph.pl:4292:
Warning:    Singleton variable in branch: B
Warning: /home/duyduyduy/Documents/concept-embeddings-and-ilp/experiments/ilp/resnet50a4e5fcba_2022-03-05_193601490481/aleph.pl:7088:
Warning:    Singleton variable in branch: Hash
Warning: /home/duyduyduy/Documents/concept-embeddings-and-ilp/experiments/ilp/resnet50a4e5fcba_2022-03-05_193601490481/aleph.pl:9215:
Warning:    Test is always true: var(Id)
`
`ERROR: /home/duyduyduy/Documents/concept-embeddings-and-ilp/experiments/ilp/resnet50a4e5fcba_2022-03-05_193601490481/aleph.pl:10410:
ERROR:    clean_up/0: Unknown procedure: gc/0
Warning: /home/duyduyduy/Documents/concept-embeddings-and-ilp/experiments/ilp/resnet50a4e5fcba_2022-03-05_193601490481/aleph.pl:10410:
Warning:    Goal (directive) failed: user:(aleph_version(_52002),set(version,_52002),reset)
ERROR: /home/duyduyduy/Documents/concept-embeddings-and-ilp/experiments/ilp/resnet50a4e5fcba_2022-03-05_193601490481/run.pl:1:
ERROR:    clean_up/0: Unknown procedure: gc/0
Warning: /home/duyduyduy/Documents/concept-embeddings-and-ilp/experiments/ilp/resnet50a4e5fcba_2022-03-05_193601490481/run.pl:1:
Warning:    Goal (directive) failed: user:([aleph],read_all(faces),induce)`

It would be so kind if you could provide me some more insights on how to solve this.

Best regards,

Anh-Duy Pham

**Comment by mc-lovin-mlem** [comment]
Hey Anh-Duy,

can you tell me which system you use for the Prolog backend? Meaning, is it something like YAP, SWI-Prolog or something else? 
Thanks and best

Johannes

**Comment by a11to1n3** [comment]
Hey Johannes,

I’m using SWI-Prolog as the ILP backend.

Best,

Anh-Duy Pham

**Comment by mc-lovin-mlem** [comment]
Hi,

I have looked inside the issue and I think that SWI-Prolog might not be well suited for our framework. We will try to make it work anyway but that can last a long time since this project is not actively maintained anymore. Have you tried using it with another Prolog backend like YAP?

**Comment by a11to1n3** [comment]
Hey,

YAP works for me. Thank you very much for your support. I'd close this issue then.

Best regards,

Anh-Duy Pham
